baseURL = 'https://feralferous.com/'
languageCode = 'en-us'
title = 'Feral-ferous'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
#[menu]
#	[[menu.main]]
#		name = "Home"
#		url = "/"
#		weight = 10
#
#	[[menu.main]]
#		name = "About"
#		url = "/about"
#		weight = 20
#
#	[[menu.main]]
#		name = "Performance"
#		url = "/performance"
#		weight = 30
#
#	[[menu.main]]
#		name = "Contact"
#		url = "/contact"
#		weight = 40